{
 "title": "Ambiente Operativo Meteo",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "HostName",
    "query": "Select FromHost from SystemEvents where FromHost like '%arpav%' or FromHost like '%testv%'group by FromHost"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "vonage-status-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "HostName",
   "targets": [
    {
     "displayType": "Regular",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  COUNT(FromHost) as value,\n  CAST(Priority as CHAR(1)) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) \nGROUP BY FromHost\nORDER BY ReceivedAt ASC\n\n\n",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "ERRORI",
   "type": "natel-discrete-panel",
   "description": "1=CRIT",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n  CAST(Priority as CHAR(1)) as metric,\n  FROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) \ngroup by time_sec,metric\nORDER BY ReceivedAt ASC"
    }
   ]
  },
  {
   "title": "Stato Sensori",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT ReceivedAt, FromHost, Message from SystemEvents where Message like '%STATOSENSORI%' and Message like \"%disponibili su FTP%\" "
    }
   ]
  },
  {
   "title": "Errori PREVISORE",
   "type": "graph",
   "description": "1=CRIT; 2=ALARM; 3=ERR;4=WARN",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n  CAST(Priority as CHAR(1)) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) and\nSyslogTag like \"%PREVISORE%\"\nand Priority in ('1','2','3')\ngroup by time_sec,metric\nORDER BY ReceivedAt ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n  CAST(Priority as CHAR(1)) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) and\nSyslogTag like \"%PREVISORE%\"\nand Priority in ('4','5','6')\ngroup by time_sec,metric\nORDER BY ReceivedAt ASC"
    }
   ]
  },
  {
   "title": "Errori ECMWF",
   "type": "graph",
   "description": "1=CRIT; 2=ALARM; 3=ERR;4=WARN",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n  CAST(Priority as CHAR(1)) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) and\nSyslogTag like \"%ECMWF%\"\ngroup by time_sec,metric\nORDER BY ReceivedAt ASC\n\n"
    }
   ]
  },
  {
   "title": "Errori DATI",
   "type": "graph",
   "description": "1=CRIT; 2=ALARM; 3=ERR;4=WARN",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n  CAST(Priority as CHAR(1)) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) and\nSyslogTag like \"%DATI%\"\ngroup by time_sec,metric\nORDER BY ReceivedAt ASC\n\n"
    }
   ]
  },
  {
   "title": "Messaggi IRIS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(ReceivedAt) as time_sec,\n  Count(ReceivedAt) as value,\n Substring(SyslogTag,1,20) as metric\nFROM SystemEvents\nWHERE $__timeFilter(ReceivedAt) and\nSyslogTag like \"%IRIS%\"\n\nGroup by time_sec,Substring(SyslogTag,1,20)\nORDER BY ReceivedAt ASC"
    }
   ]
  }
 ]
}