{
 "title": "Mondo Dati",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "RITARDI (minuti)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    \n  timestamp(data_e_ora) as time ,       \n  TIMESTAMPDIFF(MINUTE,os.Data,data_e_ora) as Aria    \nFROM \n  M_Osservazioni_TR as os ,          \n  A_Sensori as sn,           \n  A_Stazioni as st    \n\nWHERE      \n  os.IDsensore=sn.IDsensore  \n\nAND      \n  sn.IDstazione=st.IDstazione    \n\nAND     \n  AggregazioneTemporale=10  \n\nAND      \n  IDrete=1\n\nORDER BY data_e_ora asc;\n"
    }
   ]
  },
  {
   "title": "DispoDati",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\n  timestamp(data_e_ora) as time ,  \n  100*(count(data_e_ora)/(select count(IDsensore) from A_Sensori as sn, A_Stazioni as st where sn.IDstazione=st.IDstazione and IDrete=4 and Storico=\"No\" and Importato=\"Yes\" and AggregazioneTemporale=10)) as INM \n\nFROM M_Osservazioni_TR as os ,\n     A_Sensori as sn, \n     A_Stazioni as st \n\nWHERE os.IDsensore=sn.IDsensore \nAND sn.IDstazione=st.IDstazione  \nAND AggregazioneTemporale=10 \nAND IDrete=4 \n\nGROUP BY data_e_ora \nORDER BY data_e_ora asc;\n\n"
    },
    {
     "rawSql": "SELECT \n\n  timestamp(data_e_ora) as time ,  \n  100*(count(data_e_ora)/(select count(IDsensore) from A_Sensori as sn, A_Stazioni as st where sn.IDstazione=st.IDstazione and IDrete=1 and Storico=\"No\" and Importato=\"Yes\" and AggregazioneTemporale=10)) as Aria \n\nFROM M_Osservazioni_TR as os ,\n     A_Sensori as sn, \n     A_Stazioni as st \n\nWHERE os.IDsensore=sn.IDsensore \nAND sn.IDstazione=st.IDstazione  \nAND AggregazioneTemporale=10 \nAND IDrete=1 \n\nGROUP BY data_e_ora \nORDER BY data_e_ora asc;\n"
    },
    {
     "rawSql": "SELECT \n\n  timestamp(data_e_ora) as time ,  \n  100*(count(data_e_ora)/(select count(IDsensore) from A_Sensori as sn, A_Stazioni as st where sn.IDstazione=st.IDstazione and IDrete=6 and Storico=\"No\" and Importato=\"Yes\" and AggregazioneTemporale=10)) as ALTRO \n\nFROM M_Osservazioni_TR as os ,\n     A_Sensori as sn, \n     A_Stazioni as st \n\nWHERE os.IDsensore=sn.IDsensore \nAND sn.IDstazione=st.IDstazione  \nAND AggregazioneTemporale=10 \nAND IDrete=6 \n\nGROUP BY data_e_ora \nORDER BY data_e_ora asc;\n\n"
    }
   ]
  },
  {
   "title": "Stato Sensori",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT comune,attributo,count(a.nometipologia),codice,descrizione,max(e.data_e_ora) as rilevato,max(idrete) as idrete, max(rt.data_e_ora) as lastdata\r\nfrom realtime.errori_sensori as e \r\n\r\njoin dati_di_base.anagraficasensori as a on e.idsensore=a.idsensore \r\njoin realtime.m_osservazioni_tr as rt on rt.idsensore=e.idsensore \r\n\r\nwhere rt.data_e_ora > now()-interval '1 day' \r\ngroup by comune, attributo, codice, descrizione"
    }
   ]
  },
  {
   "title": "Code=3",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT codice,count(idsensore) from realtime.errori_sensori where codice=3 group by codice;\n"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 19, "y": 15 } },
  {
   "title": "Controlli sulla Rete",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 19 },
   "content": "Elenco delle risorse utili: </br>\n\n\n<a href=\"http://10.10.0.6/applications/NonComunicanti_DQCquotidiano/NC_UltimeOre.txt\"> Non Comunicanti Ultime Ore</a></br>\n\n<a href=\"http://10.10.0.6/applications/NonComunicanti_DQCquotidiano/NC_Ieri.txt\"> Non Comunicanti Ieri</a></br>\n<a href=\"http://10.10.0.6/applications/NonComunicanti_DQCquotidiano/NC_Ieri_AltreReti.txt\">Non Comunicanti Altre Reti</a></br>\n<a href=\"http://10.10.0.6/applications/NonComunicanti_DQCquotidiano/NC_AltroIeri.txt\">Non Comunicanti altro ieri</a> </br>\n\nRapporti qualità (short version)</br>\n<a href=\"http://10.10.0.6/applications/NonComunicanti_DQCquotidiano/DQC_short/dqcreport_shrt__UltimeOre.txt\">Data Quality Check ultime ore</a> </br>\n\n\n"
  },
  {
   "title": "Code=2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT codice,count(idsensore) from realtime.errori_sensori where codice=2 group by codice;\n"
    }
   ]
  },
  {
   "title": "Elenco stazioni e sensori",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensori in ritardo > 3h",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT max(data_e_ora) as time, max(an.idrete) as idrete, count(comune), comune, attributo from realtime.m_osservazioni_tr as r join dati_di_base.anagraficasensori as an on r.idsensore = an.idsensore  where now()-data_e_ora > interval '24 hour' and now()-data_e_ora< interval '48 hour' group by comune,attributo limit 100 "
      }
     ]
    },
    {
     "title": "# dati x stazione e sensore",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT extract (day from  data_e_ora) as d, extract (hour from  data_e_ora) as h,comune, attributo,r.nometipologia, count(r.nometipologia),  max (an.frequenza) as freq\r\nfrom realtime.m_osservazioni_tr as r \r\njoin dati_di_base.anagraficasensori as an on r.idsensore = an.idsensore \r\nwhere extract(day from data_e_ora)=extract(day from now())\r\nand an.frequenza < 60\r\ngroup by d, h,comune,attributo,r.nometipologia  order by comune,h asc"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n avg(cast(extract(epoch from data+ interval '1 hour') as integer) - cast (extract(epoch from data_e_ora) as integer)) as value,\n  to_char(idsensore,'99999') as metric\nFROM realtime.m_osservazioni_tr\nwhere data > date 'yesterday'\ngroup by time,to_char(idsensore,'99999')\norder by time\n\n\n"
      }
     ]
    }
   ]
  },
  { "title": "Grafici Sensori", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Anemometri",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "# sensori" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n  count(data_e_ora) as value,\n  nometipologia as metric\nFROM realtime.m_osservazioni_tr \nWHERE \nnometipologia='VV' or nometipologia='DV'\ngroup by nometipologia, data_e_ora\norder by time asc\n\n"
    }
   ]
  },
  {
   "title": "Barometri&Radiometri",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "# sensori" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n  count(data_e_ora) as value,\n  nometipologia as metric\nFROM realtime.m_osservazioni_tr \nWHERE \nnometipologia='PA' or nometipologia='RG'\ngroup by nometipologia, data_e_ora\norder by time asc\n"
    }
   ]
  },
  {
   "title": "Termometri",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "# sensori" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n  count(data_e_ora) as value,\n  nometipologia as metric\nFROM realtime.m_osservazioni_tr \nWHERE \nnometipologia='T' or nometipologia='UR'\ngroup by nometipologia, data_e_ora\norder by time asc\n\n"
    }
   ]
  },
  {
   "title": "Pluviometri e Idrometri",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "# sensori" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n  count(data_e_ora) as value,\n  nometipologia as metric\nFROM realtime.m_osservazioni_tr \nWHERE \nnometipologia='I' or nometipologia='PP'\ngroup by nometipologia, data_e_ora\norder by time asc"
    }
   ]
  },
  {
   "title": "IRIS Dati",
   "type": "graph",
   "description": "1=INM; 2=CMG; 4=RRQA",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\ntimestamptz(data_e_ora) as time,\n  count(data_e_ora) as value,\n  CAST(idrete as VARCHAR(1)) as metric\nFROM realtime.m_osservazioni_tr as rt join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \ngroup by time,metric\norder by time\n\n"
    }
   ]
  }
 ]
}