{
 "title": "Ritardi",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Stato Sensori",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT comune,attributo,count(a.nometipologia),codice,descrizione,max(e.data_e_ora) as rilevato,max(idrete) as idrete, max(rt.data_e_ora) as lastdata\r\nfrom realtime.errori_sensori as e \r\n\r\njoin dati_di_base.anagraficasensori as a on e.idsensore=a.idsensore \r\njoin realtime.m_osservazioni_tr as rt on rt.idsensore=e.idsensore \r\n\r\nwhere rt.data_e_ora > now()-interval '1 day' \r\ngroup by comune, attributo, codice, descrizione"
    }
   ]
  },
  {
   "title": "Ritardo idrometri",
   "type": "heatmap",
   "description": "deve esserci una riga continua bianca alla base",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nan.comune as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere an.nometipologia='I' and data_e_ora > now()-interval '1 day' and idrete=4\n"
    }
   ]
  },
  {
   "title": "Ritardo tutti i sensori",
   "type": "heatmap",
   "description": "deve esserci una riga continua bianca alla base",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nautore as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere data_e_ora > now()-interval '2 day' and idrete=4\norder by data_e_ora\n"
    }
   ]
  },
  {
   "title": "Ritardo sensori RRQA",
   "type": "heatmap",
   "description": "deve esserci una riga continua bianca alla base",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nan.comune as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere data_e_ora > now()-interval '2 day' and idrete=1\n"
    }
   ]
  },
  {
   "title": "Ritardo sensori non UO",
   "type": "heatmap",
   "description": "deve esserci una riga continua bianca alla base",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nan.comune as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere data_e_ora > now()-interval '2 day' and idrete in (2,3,5,6,7,8)\n"
    }
   ]
  },
  {
   "title": "Ritardo sensori in recupero",
   "type": "heatmap",
   "description": "deve esserci una riga continua bianca alla base",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nan.comune as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere data_e_ora > now()-interval '2 day' and idrete in (1,4) and autore like 'recupero%'\n"
    }
   ]
  },
  {
   "title": "Alimentazione idrometri",
   "type": "grafana-piechart-panel",
   "description": "75b alimentazione diretta\naba alimentazione 5 minuti\n99b recupero",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nautore as metric from realtime.m_osservazioni_tr\nwhere nometipologia='I' and $__timeFilter(data_e_ora)\n"
    }
   ]
  },
  {
   "title": "Alimentazione complessiva",
   "type": "grafana-piechart-panel",
   "description": "75b alimentazione diretta\naba alimentazione 5 minuti\n99b recupero",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora- interval '2 hours'),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nautore as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere $__timeFilter(data_e_ora) and idrete=4\n"
    }
   ]
  },
  {
   "title": "Distribuzione recuperi (last 12h)",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select  $__time(data_e_ora- interval '2 hours'),\nEXTRACT( epoch from (data+interval '1 hour' -data_e_ora)) as value,  \nautore as metric\n\nfrom realtime.m_osservazioni_tr as rt right outer join dati_di_base.anagraficasensori as an on rt.idsensore=an.idsensore \nwhere data_e_ora > now()-interval '12 hour' and idrete=4\n"
    }
   ]
  }
 ]
}